services:
  db:
    image: postgres:16-alpine
    container_name: project-solutions-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ProjectDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      
  api:
    image: projectsolutions-api
    container_name: projectsolutions-api
    build:
      context: . 
      dockerfile: ProjectAPI/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=application_manager_db;Username=postgres;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data: